### PR TITLE
#16 Move everything under package cats.effect.testing

### PR DESCRIPTION
**Pull request by Slakah**
See: #16

### CODE REVIEW

**Comment by Slakah** [comment]
@djspiewak , looks like this will result in binary incompatibilities. Feels like it should be possible to offer binary compat using a pattern similar to https://github.com/circe/circe/blob/4aae26ab3eed57a8320bc95645bf22af48754b54/modules/core/shared/src/main/scala/io/circe/package.scala#L3 . Dunno whether this would work for abstract classes though.

Any recommendations would be greatly appreciated!

**Comment by djspiewak** [comment]
I think it's better just to break compatibility! We're still in 0.x land. Once we get to 1.0 we'll lock things down a bit more aggressively.

So in order to break compatibility, you need to increment the `baseVersion` setting in `build.sbt`. That should make mima happy

**Comment by Slakah** [comment]
@djspiewak , bumped the version for the mima check. Should be good to go now.

**Comment by Slakah** [comment]
Thanks for the merge @djspiewak !

**Pull request merged**
