### PR TITLE
Make CatsResource compatible with AsyncIOSpec

### PR DESCRIPTION
**Pull request by Grogs**
Update `CatsResource` to be used with ScalaTest's async testing styles, rather than the synchronous ones. This allows it to be used with `AsyncIOSpec`. The example usage in `CatsResourceSpecs` is updated.

_Note: Previously the IOs created inside CatsResourceSpecs were not being executed. You can verify this by changing the assertion in seeing the test is still green without this change._

### CODE REVIEW

**Comment by Grogs** [comment]
The MiMA check is failing. This is a breaking change. I'm not sure how you want to handle that. Either accept the break or I could create `CatsAsyncResource` and leave the existing one as-is. 🤔

**Comment by fchaillou** [comment]
Hello,
I was trying to reuse that to implement the same for Monix.
I think the actual test (https://github.com/djspiewak/cats-effect-testing/blob/master/scalatest/src/test/scala/cats/effect/testing/scalatest/CatsResourceSpecs.scala) is not working because the resource is a ref that returns an IO and basically both tests return an IO[Assertion] which is ignored by scalatest.

Maybe we could keep the sync and add an async for the rare case when someone use a resource in a complete pure fashion without need of effect.

**Comment by djspiewak** [comment]
I think a change like this is worth breaking bincompat. Also really sorry for taking so long on this one!

**Comment by djspiewak** [comment]
> Maybe we could keep the sync and add an async for the rare case when someone use a resource in a complete pure fashion without need of effect.

I'm not sure I understand the context here? I feel like we're running afoul of the fact that I never use scalatest.

**Comment by fchaillou** [comment]
> 
> 
> > Maybe we could keep the sync and add an async for the rare case when someone use a resource in a complete pure fashion without need of effect.
> 
> I'm not sure I understand the context here? I feel like we're running afoul of the fact that I never use scalatest.

I'm not sure this is necessary, i think the current state is perfect and can take care also of all use cases, you should merge it like that.

**Comment by djspiewak** [comment]
Update on this! I want to get this in as soon as possible. However, right now I'm trying to avoid rocking compatibility boats too hard due to the ongoing ecosystem migration to Scala 3 and Cats Effect 3.. Given that this is specifically hitting ScalaTest, it might not be too much of a concern, but that's basically the hold-up right now in general.

**Comment by djspiewak** [comment]
Actually as soon as I write that… let's just yolo

**Pull request merged**
